pub mod ack_router;
pub mod canary;
pub mod sequence_nat;

// Include the generated proto module if available or stub definitions
#[allow(clippy::all)]
pub mod proto {
    // In standard build this is generated by prost-build
    // pub use crate::gen::zalo::packet::*;
}

pub use ack_router::{AckRouter, PacketOrigin, PendingRequest};
pub use canary::CanaryDriftDetector;
pub use sequence_nat::SequenceNat;
